settings:
  lobby-world: 'Lobby'
  login-timeout-seconds: 60
  bypass:
    - 'Milekz21'
messages:
  prefix: '&6&lMSurvivalAuth &8» &r'
  register: '&eZarejestruj konto: &6/register <hasło>'
  login: '&eZaloguj się: &6/login <hasło>'
  registered: '&aZarejestrowano i zalogowano.'
  logged: '&aZalogowano.'
  wrong: '&cBłędne hasło.'
  timeout: '&cNie zalogowałeś się na czas.'
