settings:
  premium-auto-login: true
  bypass:
    - 'Milekz21'
messages:
  prefix: '&6&lAuth &8» &r'
  register: '&eZarejestruj się: &6/register <hasło>'
  login: '&eZaloguj się: &6/login <hasło>'
  ok: '&aZalogowano.'
  wrong: '&cBłędne hasło.'
  premium: '&aKonto premium: automatycznie zalogowano.'
