name: MSurvivalAuth
version: 3.2
main: pl.msurvival.auth.MSurvivalAuth
api-version: '1.21'
author: Milekz
commands:
  register:
    usage: /register <haslo>
  login:
    usage: /login <haslo>
  authbypass:
    usage: /authbypass <add|remove|list> [gracz]
  resetpassword:
    usage: /resetpassword <gracz>
permissions:
  msurvival.auth.admin:
    default: op
