name: MSurvivalAuth
version: 5.8
main: pl.msurvival.auth.MSurvivalAuth
api-version: 5.8
author: Milekz
commands:
  register:
    usage: /register <haslo>
    aliases: [reg]
  login:
    usage: /login <haslo>
    aliases: [l]
  changepassword:
    usage: /changepassword <stare> <nowe>
  authbypass:
    usage: /authbypass <add|remove|list> [gracz]
  authforce:
    usage: /authforce <add|remove|list> [gracz]
permissions:
  msurvival.auth.admin:
    default: op
