name: MSurvivalCompass
version: 5.1
main: pl.msurvival.compass.MSurvivalCompass
api-version: 5.1
author: Milekz
commands:
  lobby:
    usage: /lobby
    aliases: [hub]
  survival:
    usage: /survival
  menu:
    usage: /menu
  compassreload:
    usage: /compassreload
permissions:
  msurvival.compass.admin:
    default: op
