name: MSurvivalCompass
version: 5.3
main: pl.msurvival.compass.MSurvivalCompass
api-version: 5.3
author: Milekz
commands:
  lobby:
    usage: /lobby
    aliases: [hub]
  survival:
    usage: /survival
  menu:
    usage: /menu
  compassreload:
    usage: /compassreload
  compassbypass:
    usage: /compassbypass <on|off>
permissions:
  msurvival.compass.admin:
    default: op
  msurvival.compass.bypass:
    default: op
