name: MSurvivalPro
version: 7.0
main: pl.msurvival.pro.MSurvivalPro
api-version: '1.21'
author: Milekz
commands:
  mspro:
    usage: /mspro
  profil:
    usage: /profil
  ustawienia:
    usage: /ustawienia
  warp:
    usage: /warp [nazwa]
  setwarp:
    usage: /setwarp <nazwa>
  delwarp:
    usage: /delwarp <nazwa>
  warpy:
    usage: /warpy
  event:
    usage: /event
  alert:
    usage: /alert <tekst>
  broadcastpro:
    usage: /broadcastpro <tekst>
permissions:
  msurvival.pro.admin:
    default: op
