package pl.msurvival.ranks;

import org.bukkit.*; import org.bukkit.command.*; import org.bukkit.configuration.file.YamlConfiguration; import org.bukkit.entity.Player; import org.bukkit.event.*; import org.bukkit.event.player.*; import org.bukkit.plugin.java.JavaPlugin; import org.bukkit.scoreboard.*;
import java.io.File; import java.util.*;

public final class MSurvivalRanks extends JavaPlugin implements Listener {
    private File dataFile; private YamlConfiguration data;
    public void onEnable(){saveDefaultConfig();dataFile=new File(getDataFolder(),"players.yml");try{getDataFolder().mkdirs();if(!dataFile.exists())dataFile.createNewFile();}catch(Exception ignored){}data=YamlConfiguration.loadConfiguration(dataFile);Bukkit.getPluginManager().registerEvents(this,this);Bukkit.getScheduler().runTaskTimer(this,()->Bukkit.getOnlinePlayers().forEach(this::apply),20,Math.max(20,getConfig().getLong("sidebar.update-ticks",80)));}
    public void onDisable(){save();}
    public boolean onCommand(CommandSender s, Command c, String l, String[] a){
        String cmd=c.getName().toLowerCase(Locale.ROOT);
        if(cmd.equals("rank")||cmd.equals("ranga")){Player p=a.length>0?Bukkit.getPlayerExact(a[0]):null;if(p==null&&s instanceof Player sp)p=sp;if(p!=null)s.sendMessage(color("&6&lMSurvival &8» &7Ranga: "+display(rank(p))));return true;}
        if(cmd.equals("ranksreload")){if(!admin(s))return true;reloadConfig();data=YamlConfiguration.loadConfiguration(dataFile);Bukkit.getOnlinePlayers().forEach(this::apply);s.sendMessage(msg("reload"));return true;}
        if(cmd.equals("setrank")){if(!admin(s))return true;if(a.length<2){s.sendMessage(color("&c/setrank <gracz> <ranga>"));return true;}String r=normal(a[1]);if(r==null){s.sendMessage(msg("rank-not-found"));return true;}set(a[0],r,0);Player p=Bukkit.getPlayerExact(a[0]);if(p!=null)apply(p);s.sendMessage(msg("rank-set").replace("%player%",a[0]).replace("%rank%",display(r)));return true;}
        if(cmd.equals("setranktemp")){if(!admin(s))return true;if(a.length<3){s.sendMessage(color("&c/setranktemp <gracz> <ranga> <7d/12h/30m>"));return true;}String r=normal(a[1]);long t=parse(a[2]);if(r==null||t<=0){s.sendMessage(msg("rank-not-found"));return true;}set(a[0],r,System.currentTimeMillis()+t);Player p=Bukkit.getPlayerExact(a[0]);if(p!=null)apply(p);s.sendMessage(msg("rank-temp-set").replace("%player%",a[0]).replace("%rank%",display(r)).replace("%time%",a[2]));return true;}
        if(cmd.equals("delrank")){if(!admin(s))return true;if(a.length<1)return true;set(a[0],"gracz",0);Player p=Bukkit.getPlayerExact(a[0]);if(p!=null)apply(p);s.sendMessage(msg("rank-reset").replace("%player%",a[0]));return true;}
        return true;
    }
    @EventHandler public void join(PlayerJoinEvent e){Bukkit.getScheduler().runTaskLater(this,()->apply(e.getPlayer()),20);}
    @EventHandler public void chat(AsyncPlayerChatEvent e){e.setFormat(color(prefix(rank(e.getPlayer()))+"%1$s &8» &f%2$s").replace("%","%%"));}
    private void apply(Player p){p.setPlayerListName(color(prefix(rank(p))+p.getName()));sidebar(p);}
    private void sidebar(Player p){if(!getConfig().getBoolean("sidebar.enabled",true))return;Scoreboard b=Bukkit.getScoreboardManager().getNewScoreboard();Objective o=b.registerNewObjective("msr","dummy",color(getConfig().getString("sidebar.title","&6MSURVIVAL")));o.setDisplaySlot(DisplaySlot.SIDEBAR);int sc=getConfig().getStringList("sidebar.lines").size();Set<String> used=new HashSet<>();String ex=expires(p);for(String raw:getConfig().getStringList("sidebar.lines")){if(raw.contains("%expires%")&&ex.equals("nigdy")){sc--;continue;}String line=color(raw.replace("%player%",p.getName()).replace("%rank%",display(rank(p))).replace("%expires%",ex).replace("%money%",money(p.getName())).replace("%clan%",clan(p.getName())).replace("%online%",""+Bukkit.getOnlinePlayers().size()).replace("%ping%",""+p.getPing()));while(used.contains(line))line+=ChatColor.RESET;used.add(line);if(line.length()>40)line=line.substring(0,40);o.getScore(line).setScore(sc--);}p.setScoreboard(b);}
    private void set(String player,String r,long exp){String base="players."+player.toLowerCase(Locale.ROOT);data.set(base+".rank",r);data.set(base+".expires",exp);save();}
    private String rank(Player p){String base="players."+p.getName().toLowerCase(Locale.ROOT);String r=data.getString(base+".rank","gracz");if(!getConfig().contains("ranks."+r))r="gracz";long exp=data.getLong(base+".expires",0);if(exp>0&&exp<=System.currentTimeMillis()){set(p.getName(),"gracz",0);p.sendMessage(msg("rank-expired"));return"gracz";}return r;}
    private String normal(String in){String r=in.toLowerCase(Locale.ROOT).replace("ą","a").replace("ć","c").replace("ę","e").replace("ł","l").replace("ń","n").replace("ó","o").replace("ś","s").replace("ż","z").replace("ź","z");r=getConfig().getString("aliases."+r,r);return getConfig().contains("ranks."+r)?r:null;}
    private String expires(Player p){long exp=data.getLong("players."+p.getName().toLowerCase(Locale.ROOT)+".expires",0);if(exp<=0)return"nigdy";long m=Math.max(1,(exp-System.currentTimeMillis())/60000);long h=m/60,d=h/24;if(d>0)return d+"d "+(h%24)+"h";if(h>0)return h+"h "+(m%60)+"m";return m+"m";}
    private long parse(String x){try{long v=Long.parseLong(x.substring(0,x.length()-1));char u=x.charAt(x.length()-1);return u=='d'?v*86400000L:u=='h'?v*3600000L:v*60000L;}catch(Exception e){return 0;}}
    private String money(String player){File f=new File(getDataFolder().getParentFile(),"MSurvivalMarket/balances.yml");if(!f.exists())return"0";double v=YamlConfiguration.loadConfiguration(f).getDouble("players."+player.toLowerCase(Locale.ROOT),0);return v==(long)v?String.valueOf((long)v):String.format(Locale.US,"%.2f",v);}
    private String clan(String player){File f=new File(getDataFolder().getParentFile(),"MSurvivalClans/clans.yml");if(!f.exists())return"Brak";return YamlConfiguration.loadConfiguration(f).getString("players."+player.toLowerCase(Locale.ROOT)+".clan","Brak");}
    private String display(String r){return color(getConfig().getString("ranks."+r+".display",r));} private String prefix(String r){return getConfig().getString("ranks."+r+".prefix","&7");}
    private boolean admin(CommandSender s){if(!s.hasPermission("msurvival.ranks.admin")){s.sendMessage(msg("no-permission"));return false;}return true;} private void save(){try{data.save(dataFile);}catch(Exception ignored){}} private String msg(String k){return color(getConfig().getString("messages.prefix","")+getConfig().getString("messages."+k,""));} private String color(String s){return ChatColor.translateAlternateColorCodes('&',s==null?"":s);}
}
