worlds:
  lobby: 'Lobby'
  survival: 'world'
lobby: {x: 0.5, y: 100.0, z: 0.5, yaw: 0.0, pitch: 0.0}
survival: {x: 0.5, y: 100.0, z: 0.5, yaw: 0.0, pitch: 0.0}
items:
  compass-slot: 4
  compass-name: '&6&lMSurvival Menu'
messages:
  prefix: '&6&lMSurvival &8» &r'
  lobby: '&aPrzeniesiono do lobby.'
  survival: '&aPrzeniesiono na Survival.'
  set-lobby: '&aUstawiono lobby.'
  set-survival: '&aUstawiono Survival.'
  no-permission: '&cNie masz uprawnień.'
