name: MSurvivalLobby
version: 5.8
main: pl.msurvival.lobby.MSurvivalLobby
api-version: 5.8
author: Milekz
commands:
  setlobby:
    usage: /setlobby
  setsurvival:
    usage: /setsurvival
permissions:
  msurvival.lobby.admin:
    default: op
