name: MSurvivalLobby
version: 4.5
main: pl.msurvival.lobby.MSurvivalLobby
api-version: 4.5
author: Milekz
commands:
  lobby:
    usage: /lobby
    aliases: [hub]
  survival:
    usage: /survival
  menu:
    usage: /menu
  setlobby:
    usage: /setlobby
  setsurvival:
    usage: /setsurvival
permissions:
  msurvival.lobby.admin:
    default: op
