name: MSurvivalLobby
version: 3.2
main: pl.msurvival.lobby.MSurvivalLobby
api-version: '1.21'
author: Milekz
commands:
  lobby:
    usage: /lobby
    aliases: [hub]
  survival:
    usage: /survival
  setlobby:
    usage: /setlobby
  setsurvival:
    usage: /setsurvival
  menu:
    usage: /menu
permissions:
  msurvival.lobby.admin:
    default: op
