name: MSurvivalBans
version: 7.1
main: pl.msurvival.bans.MSurvivalBans
api-version: '1.21'
author: Milekz
commands:
  msban: {usage: /msban <gracz> <powod>}
  msunban: {usage: /msunban <gracz>}
  mskick: {usage: /mskick <gracz> <powod>}
permissions:
  msurvival.bans.admin:
    default: op
