name: MSurvivalRanks
version: 6.4
main: pl.msurvival.ranks.MSurvivalRanks
api-version: '1.21'
author: Milekz
commands:
  rank:
    usage: /rank [gracz]
  ranga:
    usage: /ranga [gracz]
  setrank:
    usage: /setrank <gracz> <ranga>
  setranktemp:
    usage: /setranktemp <gracz> <ranga> <czas>
    aliases: [temprank]
  delrank:
    usage: /delrank <gracz>
  ranksreload:
    usage: /ranksreload
permissions:
  msurvival.ranks.admin:
    default: op
