name: MSurvivalRanks
version: 4.6
main: pl.msurvival.ranks.MSurvivalRanks
api-version: '1.21'
commands:
  setrank: {usage: /setrank <gracz> <ranga>}
  setranktemp: {usage: /setranktemp <gracz> <ranga> <czas>}
  rank: {usage: /rank}
permissions:
  msurvival.ranks.admin: {default: op}
