name: MSurvivalClans
version: 5.8
main: pl.msurvival.clans.MSurvivalClans
api-version: 5.8
author: Milekz
commands:
  clan:
    usage: /clan <create|invite|join|leave|info|disband>
    aliases: [klan, clany]
permissions:
  msurvival.clans.admin:
    default: op
