name: MSurvivalClans
version: 6.4
main: pl.msurvival.clans.MSurvivalClans
api-version: '1.21'
author: Milekz
commands:
  clan:
    usage: /clan <create|invite|join|leave|info|disband>
    aliases: [klan, clany]
permissions:
  msurvival.clans.admin:
    default: op
