package pl.msurvival.market;

import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.inventory.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.PersistentDataType;import org.bukkit.plugin.java.JavaPlugin;
import java.io.File;import java.util.*;

public final class MSurvivalMarket extends JavaPlugin implements Listener{
 File file;YamlConfiguration data;NamespacedKey key;
 public void onEnable(){saveDefaultConfig();key=new NamespacedKey(this,"act");file=new File(getDataFolder(),"balances.yml");try{getDataFolder().mkdirs();file.createNewFile();}catch(Exception ignored){}data=YamlConfiguration.loadConfiguration(file);Bukkit.getPluginManager().registerEvents(this,this);}
 public boolean onCommand(CommandSender s,Command c,String l,String[]a){String cmd=c.getName().toLowerCase(); if(cmd.equals("rynek")&&s instanceof Player p){open(p);return true;} if(cmd.equals("kasa")&&s instanceof Player p){p.sendMessage(color("&6&lRynek &8» &aKasa: &e"+bal(p.getName())+"$"));return true;} if((cmd.equals("sell")||cmd.equals("sellall"))&&s instanceof Player p){double e=sell(p);p.sendMessage(color("&6&lRynek &8» &aSprzedano za &e"+(long)e+"$"));return true;} if(cmd.equals("kosz")&&s instanceof Player p){p.openInventory(Bukkit.createInventory(null,54,color("&c&lKOSZ")));return true;} if(cmd.equals("rynekadmin")&&s.hasPermission("msurvival.market.admin")&&a.length>=3){add(a[1],Double.parseDouble(a[2]));return true;} return true;}
 void open(Player p){Inventory inv=Bukkit.createInventory(null,45,color("&6&lRYNEK"));fill(inv);inv.setItem(10,but(Material.BAMBOO,"&a&lSPRZEDAJ ITEMY","sell",List.of("&7Bambus i trzcina są drogie","&eKliknij: sellall")));inv.setItem(14,but(Material.TRIPWIRE_HOOK,"&6&lKLUCZE","keys",List.of("&7Wszystkie klucze za dolary")));inv.setItem(31,but(Material.GOLD_INGOT,"&a&lKASA: &e"+(long)bal(p.getName())+"$","none",List.of("&7Twoje pieniądze")));p.openInventory(inv);}
 void keys(Player p){Inventory inv=Bukkit.createInventory(null,27,color("&6&lRYNEK KLUCZY"));fill(inv);String[] ks={"klasyczny","zelazny","diamentowy","epic","legendarny","mityczny","boski"};int slot=10;for(String k:ks){double price=getConfig().getDouble("keys."+k);inv.setItem(slot++,but(Material.TRIPWIRE_HOOK,"&e&l"+k.toUpperCase(),"buy:"+k,List.of("&7Cena: &e"+(long)price+"$","&aKliknij aby kupić")));}p.openInventory(inv);}
 @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p))return;String title=e.getView().getTitle();if(!title.equals(color("&6&lRYNEK"))&&!title.equals(color("&6&lRYNEK KLUCZY")))return;e.setCancelled(true);String a=act(e.getCurrentItem());if(a==null)return;if(a.equals("sell")){double earn=sell(p);p.sendMessage(color("&a+"+(long)earn+"$"));p.closeInventory();}else if(a.equals("keys"))keys(p);else if(a.startsWith("buy:")){String k=a.substring(4);double price=getConfig().getDouble("keys."+k);if(bal(p.getName())<price){p.sendMessage(color("&cBrak kasy."));return;}add(p.getName(),-price);Bukkit.dispatchCommand(Bukkit.getConsoleSender(),"keyadmin give "+p.getName()+" "+k+" 1");p.sendMessage(color("&aKupiono klucz."));}}
 @EventHandler public void close(InventoryCloseEvent e){if(e.getView().getTitle().equals(color("&c&lKOSZ")))e.getInventory().clear();}
 double sell(Player p){double t=0;for(String m:getConfig().getConfigurationSection("sell").getKeys(false)){Material mat;try{mat=Material.valueOf(m);}catch(Exception ex){continue;}double pr=getConfig().getDouble("sell."+m);for(ItemStack it:p.getInventory().getContents())if(it!=null&&it.getType()==mat){t+=it.getAmount()*pr;it.setAmount(0);}}add(p.getName(),t);return t;}
 ItemStack but(Material m,String n,String a,List<String>l){ItemStack it=new ItemStack(m);ItemMeta meta=it.getItemMeta();meta.setDisplayName(color(n));List<String> lo=new ArrayList<>();for(String x:l)lo.add(color(x));meta.setLore(lo);meta.getPersistentDataContainer().set(key,PersistentDataType.STRING,a);it.setItemMeta(meta);return it;}
 void fill(Inventory inv){ItemStack g=but(Material.BLACK_STAINED_GLASS_PANE," ","none",List.of());for(int i=0;i<inv.getSize();i++)inv.setItem(i,g);}
 String act(ItemStack it){return it==null||!it.hasItemMeta()?null:it.getItemMeta().getPersistentDataContainer().get(key,PersistentDataType.STRING);}
 double bal(String p){return data.getDouble("players."+p.toLowerCase(),0);} void add(String p,double a){data.set("players."+p.toLowerCase(),Math.max(0,bal(p)+a));save();} void save(){try{data.save(file);}catch(Exception e){}} String color(String s){return ChatColor.translateAlternateColorCodes('&',s==null?"":s);}
}
