server:
  name: 'MSURVIVAL'
  ip: 'msurvival.6mc.pl'
  donate: 'https://tipply.pl/@milekz'
messages:
  prefix: '&6&lMSurvival &8» &r'
  reload: '&aPrzeładowano konfigurację.'
  no-permission: '&cNie masz uprawnień.'
