name: MSurvivalCore
version: 3.2
main: pl.msurvival.core.MSurvivalCore
api-version: '1.21'
author: Milekz
commands:
  mscore:
    usage: /mscore reload
permissions:
  msurvival.core.admin:
    default: op
