title: {enabled: true, title: '&6&lMSURVIVAL', subtitle: '&eWitaj na serwerze!'}
welcome:
  - '&6&l✦━━━━━━━━━━ &e&lMSURVIVAL &6&l━━━━━━━━━━✦'
  - '&b⚡ &fOficjalny serwer twórcy &e&lMilekz &b⚡'
  - '&f👋 Witaj &e&l%player%&f!'
  - '&e/pomoc &7- komendy &8| &e/keysmenu &7- klucze &8| &e/kits &7- E-Kity &8| &e/rynek &7- rynek'
  - '&6&lmsurvival.6mc.pl'
help:
  - '&6&lMSURVIVAL &8» &fKomendy'
  - '&e/pomoc &8- &7komendy'
  - '&e/keysmenu &8- &7klucze'
  - '&e/kits &8- &7E-Kity'
  - '&e/rynek &8- &7rynek'
donate:
  - '&6Donate: &bhttps://tipply.pl/@milekz'
