name: MSurvivalWelcome
version: 5.0
main: pl.msurvival.welcome.MSurvivalWelcome
api-version: 5.0
author: Milekz
commands:
  pomoc: {usage: /pomoc}
  komendy: {usage: /komendy}
  regulamin: {usage: /regulamin}
  donate: {usage: /donate}
