name: MSurvivalWelcome
version: 6.5
main: pl.msurvival.welcome.MSurvivalWelcome
api-version: '1.21'
author: Milekz
commands:
  pomoc:
    usage: /pomoc
  regulamin:
    usage: /regulamin
  media:
    usage: /media
  donate:
    usage: /donate
  welcome:
    usage: /welcome reload
  skipwelcome:
    usage: /skipwelcome
    aliases: [skipintro]
permissions:
  msurvival.welcome.admin:
    default: op
