name: MSurvivalWelcome
version: 6.1
main: pl.msurvival.welcome.MSurvivalWelcome
api-version: 6.1
author: Milekz
commands:
  pomoc:
    usage: /pomoc
  regulamin:
    usage: /regulamin
  media:
    usage: /media
  donate:
    usage: /donate
  welcome:
    usage: /welcome reload
permissions:
  msurvival.welcome.admin:
    default: op
