settings:
  survival-world: 'world'
  weekly-cooldown-seconds: 604800

key-item:
  material: TRIPWIRE_HOOK
  name: '&6&l✦ %key_name% &6&l✦'
  lore:
    - '&8━━━━━━━━━━━━━━━━'
    - '&7Typ: %key_name%'
    - '&7Przedmiot: &eZaczep na linkę'
    - ''
    - '&fTo jest klucz do &bE-Kita&f.'
    - '&cNie klikaj PPM.'
    - '&7Wejdź na &aSurvival &7i użyj &e/kits&7.'
    - '&8━━━━━━━━━━━━━━━━'

keys:
  klasyczny: '&f&lKlucz Klasyczny'
  zelazny: '&7&lKlucz Żelazny'
  diamentowy: '&b&lKlucz Diamentowy'
  epic: '&5&lKlucz Epic'
  legendarny: '&6&lKlucz Legendarny'
  mityczny: '&d&lKlucz Mityczny'
  boski: '&4&lKlucz Boski'

weekly:
  klasyczny: 85
  zelazny: 15

messages:
  prefix: '&6&lMSurvival &8» &r'
  no-permission: '&cNie masz uprawnień.'
  only-survival: '&cE-Kity i fizyczne klucze odbierasz tylko na &aSurvivalu&c.'
  withdrawn: '&a✔ Wyjęto klucz: %key%'
  claimed: '&a✔ Odebrałeś klucz: %key%'
  no-key: '&c✘ Nie masz wymaganego klucza: %key%'
  opened: '&a✔ Otworzono E-Kit: &e%kit%'
  cooldown: '&cCotygodniowy klucz odbierzesz za: &e%time%'
  disabled-ppm: '&cTego klucza nie otwierasz PPM. Użyj &e/kits&c.'
  admin-give: '&aDodano &e%amount%x %key% &adla &e%player%&a.'
