settings:
  survival-world: 'world'
  weekly-cooldown-seconds: 604800

key-item:
  material: TRIPWIRE_HOOK

keys:
  klasyczny: '&f&lKlucz Klasyczny'
  zelazny: '&7&lKlucz Żelazny'
  diamentowy: '&b&lKlucz Diamentowy'
  epic: '&5&lKlucz Epic'
  legendarny: '&6&lKlucz Legendarny'
  mityczny: '&d&lKlucz Mityczny'
  boski: '&4&lKlucz Boski'

messages:
  prefix: '&6MSurvival &8» &r'
  no-permission: '&cNie masz uprawnień.'
  only-survival: '&cKlucze i E-Kity odbierasz tylko na Survivalu.'
  disabled-ppm: '&cKlucza nie używasz PPM. Otwórz /kits.'
  no-key: '&cNie masz klucza: %key%'
  withdrawn: '&aWyjęto klucz: %key%'
  admin-give: '&aDodano &e%amount%x %key% &adla &e%player%'
  opened: '&aOtworzono E-Kit: &e%kit%'
  weekly-ready:
    - '&6Cotygodniowy klucz &8» &aMożesz odebrać swój klucz komendą &e/weeklykey&a.'
    - '&7Szanse: Klasyczny 89.0000%, Żelazny 10.0000%, Diamentowy 0.9000%, Epic 0.0900%, Legendarny 0.0090%, Mityczny 0.0002%, Boski 0.0001%.'
  weekly-claimed:
    - '&6Cotygodniowy klucz &8» &aOdebrano klucz.'
    - '&7Wylosowano: %key%'
    - '&7Szanse: Klasyczny 89.0000%, Żelazny 10.0000%, Diamentowy 0.9000%, Epic 0.0900%, Legendarny 0.0090%, Mityczny 0.0002%, Boski 0.0001%.'
  weekly-cooldown:
    - '&6Cotygodniowy klucz &8» &cKlucz został już odebrany.'
    - '&7Następny odbiór za: &e%time%'
