name: MSurvivalKeys
version: 6.4
main: pl.msurvival.keys.MSurvivalKeys
api-version: '1.21'
author: Milekz
commands:
  keysmenu:
    usage: /keysmenu
    aliases: [key, keys, klucze]
  kits:
    usage: /kits
    aliases: [kit, ekit, ekits]
  weeklykey:
    usage: /weeklykey
  keyadmin:
    usage: /keyadmin <give|item> <gracz> <klucz> [ilosc]
permissions:
  msurvival.keys.admin:
    default: op
